# 池田館の監視対象（日付は最大3件まで指定できます）
target_year: 2026

target_days:
  - month: 8
    day: 16
  - month: 8
    day: 17
  - month: 9
    day: 4

# 大部屋・2人部屋・3人部屋のいずれか1つでも空いたら通知
target_rooms:
  - "大部屋"
  - "2人部屋"
  - "3人部屋"
